### ISSUE TITLE
Add config to specify encoding for Macro Strings

### ISSUE THREAD

**Issue by mannprerak2** [dart-lang/ffigen#107]
Macro Strings are considered as Utf8 by default, but we have no way to know the encoding used. 
E.g the Linux POSIX API uses Extended ASCII in their macro strings. 
We should add a config to let the user specify the encoding to use. 

Perhaps something like this -
```yaml
macros:
  ...
  encoding:
    - 'TXIP_.*': ascii # options 
```

We should support these options at very least - `ascii`, `utf8`(default).

Another config option could be `raw` which generates a `Uint8List` instead of a String.
