### ISSUE TITLE
Header files including math.h generate erroneous bindings

### ISSUE THREAD

**Issue by illright** [dart-lang/ffigen#112]
Consider a simple `ffigen-config.yaml`:
```yaml
output: 'file.dart'
headers:
  entry-points:
    - './test.h'
```

And the `test.h` file which is just a single include directive:
```c
#include <math.h>
```

This generates a large bindings file, but one part of it seems to violate the Dart analyzer:
```dart
const double HUGE_VAL = Infinity;

const double HUGE_VALF = Infinity;

const double HUGE_VALL = Infinity;

const double INFINITY = Infinity;

const double NAN = NaN;
```

`Infinity` and `NaN` are not valid Dart constants, and instead should be `double.infinity` and `double.nan` respectively.
