### ISSUE TITLE
Given include-directives are not used properly

### ISSUE THREAD

**Issue by hacker1024** [dart-lang/ffigen#123]
I'm trying to generate bindings for macOS's IOKit. Here's the configuration:

```yaml
ffigen:
  name: 'IOKit'
  description: 'Dart bindings for IOKit'
  output: 'lib/src/iokit_ffi_bindings.dart'
  headers:
    entry-points:
      - '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h'
    include-directives:
      - '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/**'
```

The given include files do not seem to be used, however, as the generation fails with the following error:
```
[SEVERE] : Header /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h: Total errors/warnings: 1.
[SEVERE] :     /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:39:10: fatal error: 'sys/cdefs.h' file not found [Lexical or Preprocessor Issue]
```

The include-directive is reported as being used when enabling verbose logging:

```
[FINEST] : Config Map: {name: IOKit, description: Dart bindings for IOKit, output: lib/src/iokit_ffi_bindings.dart, headers: {entry-points: [/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h], include-directives: [/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/**]}}
```

Using the following directive also does not work, so the wildcard isn't the problem here:
`/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h`

I'd expect ffigen to use the given include files, but it isn't.
