### ISSUE TITLE
`typedef struct {} TYPE, *pType;` results in `class pType`

### ISSUE THREAD

**Issue by Sunbreak** [dart-lang/ffigen#157]
https://github.com/twain/twain-dsm/blob/master/TWAIN_DSM/src/twain.h#L443-L456

```c
// C
typedef struct {
    TW_UINT32 	   Id;
    TW_VERSION 	   Version;
    TW_UINT16  	   ProtocolMajor;
    TW_UINT16  	   ProtocolMinor;
    TW_UINT32  	   SupportedGroups;
    TW_STR32   	   Manufacturer;
    TW_STR32   	   ProductFamily;
    TW_STR32   	   ProductName;
} TW_IDENTITY, FAR * pTW_IDENTITY;

// function
TW_UINT16 TW_CALLINGSTYLE DSM_Entry( pTW_IDENTITY pOrigin,
                                pTW_IDENTITY pDest,
                                TW_UINT32    DG,
                                TW_UINT16    DAT,
                                TW_UINT16    MSG,
                                TW_MEMREF    pData);
```

results in

```dart
// Dart
class pTW_IDENTITY extends ffi.Struct {}

// function
  int DSM_Entry(
    ffi.Pointer<pTW_IDENTITY > pOrigin,
    ffi.Pointer<pTW_IDENTITY > pDest,
    int DG,
    int DAT,
    int MSG,
    ffi.Pointer<ffi.Void> pData,
  )
```

**Comment by Sunbreak** [comment]
After change C code to

```c
// C
struct TW_IDENTITY {
    TW_UINT32 	   Id;
    TW_VERSION 	   Version;
    TW_UINT16  	   ProtocolMajor;
    TW_UINT16  	   ProtocolMinor;
    TW_UINT32  	   SupportedGroups;
    TW_STR32   	   Manufacturer;
    TW_STR32   	   ProductFamily;
    TW_STR32   	   ProductName;
};

typedef TW_IDENTITY * pTW_IDENTITY;
```

Dart code is generated as expected

```dart
// Dart
class TW_IDENTITY extends ffi.Struct {}

// function
  int DSM_Entry(
    ffi.Pointer<TW_IDENTITY > pOrigin,
    ffi.Pointer<TW_IDENTITY > pDest,
    int DG,
    int DAT,
    int MSG,
    ffi.Pointer<ffi.Void> pData,
  )
```

**Comment by mannprerak2** [comment]
This is only a name issue. Both `TW_IDENTITY` or `pTW_IDENTITY` are the same structs (only 1 is generated by ffigen).
So you can consider both the struct names as equivalent.

```C
typedef struct {
   int a;
} TW_VERSION, *pTW_VERSION;
```
For a struct like this ffigen will pick up the last name (`pTW_VERSION`) as the name of the struct.

Note that this does not happen if you do this
```C
struct TW_VERSION{
   int a;
};
typedef struct TW_VERSION *pTW_VERSION; // Now this is ignored.
```
See this for the exact rules we follow for setting the name of a struct - https://github.com/dart-lang/ffigen/pull/83#issue-468727439

---
For ffigen, I think we should **try not to use** the typedefs names if they refer to `struct *` instead of `struct`, as this may not always be possible. E.g to be able to generate this struct, we'd either have to use a random name or use this name even though it refers to a `struct *`.
```C
typedef struct {
   int a;
} *pMyStruct;
```

**Comment by Sunbreak** [comment]
OK. I would try `structs-rename` like: https://github.com/Sunbreak/logic_conf.dart/blob/e4935e68399987d61262b3a7d20d0a2c38808471/windows/hidsdi.yaml#L11

```yaml
structs:
  rename:
    '_HIDP_PREPARSED_DATA': 'HIDP_PREPARSED_DATA'
```

**Comment by mannprerak2** [comment]
Yes sure, you can do that for now.

**Comment by Sunbreak** [comment]
`Struct`s in included headers works, but not `Struct`s in dependency

In https://github.com/Sunbreak/logic_conf.dart/commit/cc4cfc7771e064017b377f9a8ccfa89807cd1ed0, `PSP_DEVINFO_DATA` is not ignored.

- SetupAPI.yaml

```yaml
name: SetupAPI
description: Bindings to `SetupAPI.h`.
llvm-lib: 'C:\Program Files\LLVM\bin'
output: 'lib/src/windows/setupapi.dart'
headers:
  entry-points:
    - 'windows/SetupAPI_.h'
  include-directives: # include only these header files and necessary structs from other header files
    - '**SetupAPI_.h'
array-workaround: true
size-map:
  long: 4
  unsigned long: 4
```

- SetupAPI_.h

```c
WINSETUPAPI
BOOL
WINAPI
SetupDiEnumDeviceInterfaces(
    _In_ HDEVINFO DeviceInfoSet,
    _In_opt_ PSP_DEVINFO_DATA DeviceInfoData,
    _In_ CONST GUID *InterfaceClassGuid,
    _In_ DWORD MemberIndex,
    _Out_ PSP_DEVICE_INTERFACE_DATA DeviceInterfaceData
    );

// Struct3 is used. `pStruct2` and `pStruct3` are ignored.
typedef struct
{
} Struct2, Struct3, *pStruct2, *pStruct3;
```

- setupapi.dart

```dart
  int SetupDiEnumDeviceInterfaces(
    ffi.Pointer<ffi.Void> DeviceInfoSet,
    ffi.Pointer<PSP_DEVINFO_DATA> DeviceInfoData,
    ffi.Pointer<GUID> InterfaceClassGuid,
    int MemberIndex,
    ffi.Pointer<PSP_DEVICE_INTERFACE_DATA> DeviceInterfaceData,
  )

class Struct3 extends ffi.Opaque {}
```

**Comment by mannprerak2** [comment]
Yes @Sunbreak, this has been mentioned in the PR as well  
https://github.com/dart-lang/ffigen/pull/172#issue-583935976.

The reason for this is how we name structs, a struct can have multiple names (Atmost 1 in the struct namespace and possibly many in the global namespace using typedefs). We have no possibile way to choose a particular name from all of them.

If the user includes a particular name, we use that one, but if they don't we use whatever name a function has used.

So currently there are 2 ways to go from here.
1. You include the struct names you need, so that the exact name is generated. But this also means not using the include-directives key which will exclude structs from a particular header.
2. Rename the structs you need to, note that you can also use regexp here, you can possibly match something like this -
```yaml
structs:
  rename:
    'p([A-Z].*)': '$1' # Remove anything which starts with pX, where X is a captial letter.
```
