### ISSUE TITLE
ffigen: output: ... create folder if it does not exist

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffigen#171]
```yaml
ffigen:
  output: 'lib/third_party/boringssl/generated_bindings.dart'
  headers:
    entry-points:
      - 'third_party/boringssl/src/include/openssl/digest.h'
```

expects `lib/third_party/boringssl` already to exist. Let's create the folder if it does not exist.
