### ISSUE TITLE
Failed to load dynamic library

### ISSUE THREAD

**Issue by MarvinHannott** [dart-lang/ffigen#183]
ffigen fails with 

> Unhandled exception:
> Invalid argument(s): Failed to load dynamic library (193)

I use LLVM 11 on Windows.

Now, I know from this [comment](https://github.com/dart-lang/sdk/issues/38450#issuecomment-644722545) that the error code 193 supposedly means that a 32-bit library is loaded. But of course, I installed the 64-bit version of LLVM, and made double certain of that, and also checked the libclang.dll with [sigcheck](https://docs.microsoft.com/en-us/sysinternals/downloads/sigcheck):

> d:\program files\llvm\bin\libclang.dll:
        Verified:       Unsigned
        Link date:      15:13 12.10.2020
        Publisher:      n/a
        Company:        n/a
        Description:    n/a
        Product:        clang
        Prod version:   11.0.0 (LLVM 11.0.0)
        File version:   11.0.0 (LLVM 11.0.0)
        **MachineType:    64-bit**

This is my configuration of ffigen: 
```yaml
ffigen:
  llvm-lib: 'D:/Program Files/LLVM/bin'
  output: 'dart_sodium.dart'
  name: 'dart_sodium'
  headers:
    entry-points:
      - 'include/sodium.h'
```
