### ISSUE TITLE
automatically add C standard library headers to compiler-opts

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffigen#190]
On MacOS, the std lib is not on the include path by default.

We should consider adding logic for searching for it in this package, and adding it to the compiler options by default.

Every project is going to have to add these to the compiler opts otherwise.

For example: https://github.com/dart-lang/ffigen/blob/master/test/large_integration_tests/large_test.dart#L82-L83

**Comment by mannprerak2** [comment]
These headers seem to be available at 2 locations -
1. `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include/`
2. If command line tools are installed `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Headers/`

We could have used **`2`** but it may not be present if the user hasn't installed command-line tools, so we can possibly only use `1` as the default location but would need to fix the **`12.0.0`** to whatever is available in the path.

**Comment by dcharkes** [comment]
We could search for versions instead of pinning them

```dart
    const brewLlvmPath = "/usr/local/opt/llvm/lib/clang";
    const commandLineToolsClangPath =
        "/Library/Developer/CommandLineTools/usr/lib/clang";
    const searchPaths = [brewLlvmPath, commandLineToolsClangPath];
    List<String> includePaths = [];
    for (final searchPath in searchPaths) {
      final result = Process.runSync('ls', [searchPath]);
      final stdout = result.stdout as String;
      if (stdout != "") {
        final versions = stdout.split("\n").where((s) => s != "");
        for (final version in versions) {
          final path = "$searchPath/$version/include";
          includePaths.add(path);
        }
      }
    }
    if (includePaths.isEmpty) {
      print("The stdlib headers could not be found.");
      print("Paths searched: $searchPaths");
      print("Install Command Line Tools.");
      print("Or, please run `brew install llvm`.");
    }
```

**Comment by dcharkes** [comment]
What about this API?

```yaml
automatic-compiler-opts:
  macos:
    # Looks for the c standard library headers in CommandLineTools, XCode, and llvm.
    # Issues a warning if headers cannot be found.
    # Automatically adds `-Ipath/to/c-standard-library` to `compiler-opts`.
    include-c-standard-library: true (default) | false
```
