### ISSUE TITLE
Unable to run ffigen on arch linux, Couldn't find dynamic library

### ISSUE THREAD

**Issue by Zwo1in** [dart-lang/ffigen#195]
Hi,
I've recently started a new experimental project using rust ffi and flutter. I've got stuck with passing structs by value and noticed that I'm using old version of both `ffi` and `ffigen`. After this upgrade
```diff
-  ffi: ^0.1.3
+  ffi: ^1.0.0
-  ffigen: ^1.2.0
+  ffigen: ^2.4.0
```
ffigen stopped finding llvm.

This minimal dockerfile is able to reproduce the issue (at least for me) however it also fails with same messages on my arch desktop:
```dockerfile
FROM archlinux:latest

ENV FLUTTER_HOME="/opt/flutter"
ENV PATH="$FLUTTER_HOME/bin:$PATH"

RUN pacman -Syu --noconfirm \
    clang gcc git jdk8-openjdk make unzip wget \
    && pacman -Scc --noconfirm

RUN git clone https://github.com/flutter/flutter.git $FLUTTER_HOME \
    && flutter channel stable \
    && flutter doctor

ENTRYPOINT sh
```
Package [clang](https://archlinux.org/packages/extra/x86_64/clang/) installs `libclang.so` to `/usr/lib` as well as [llvm-libs](https://archlinux.org/packages/extra/x86_64/llvm-libs/) however with or without `llvm-path`, ffigen is unable to find it:
```sh
> docker run -it -v `pwd`:/proj -w /proj ffigen-repr                                          
sh-5.1# file /usr/lib/libclang.so
/usr/lib/libclang.so: symbolic link to libclang.so.11.1                                                                                                                                    
sh-5.1# file /usr/lib/libclang.so.11.1
/usr/lib/libclang.so.11.1: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=411094ba7908c52e809d6932784bc7597e45c412, stripped

sh-5.1# flutter pub get && dart run ffigen
Running "flutter pub get" in proj...                                6.4s
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ The Dart tool uses Google Analytics to anonymously report feature usage    ║
  ║ statistics and to send basic crash reports. This data is used to help      ║
  ║ improve the Dart platform and tools over time.                             ║
  ║                                                                            ║
  ║ To disable reporting of anonymous analytics, run:                          ║
  ║                                                                            ║
  ║   dart --disable-analytics                                                 ║
  ║                                                                            ║
  ╚════════════════════════════════════════════════════════════════════════════╝

Precompiling executable... (2.6s)
Precompiled ffigen:ffigen.
Running in Directory: '/proj'
[WARNING]: Prefer adding Key '[name]' to your config.
[WARNING]: Prefer adding Key '[description]' to your config.
[SEVERE] : Couldn't find dynamic library in default locations.
[SEVERE] : Please supply one or more path/to/llvm in ffigen's config under the key 'llvm-path'.
Unhandled exception:
Exception: Couldn't find dynamic library in default locations.
#0      findDylibAtDefaultLocations (package:ffigen/src/config_provider/spec_utils.dart:330:3)
#1      Config._getSpecs.<anonymous closure> (package:ffigen/src/config_provider/config.dart:198:29)
#2      Config._extract (package:ffigen/src/config_provider/config.dart:174:50)
#3      new Config.fromYaml (package:ffigen/src/config_provider/config.dart:124:17)
#4      getConfigFromPubspec (package:ffigen/src/executables/ffigen.dart:104:17)
#5      getConfig (package:ffigen/src/executables/ffigen.dart:71:14)
#6      main (package:ffigen/src/executables/ffigen.dart:47:14)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
sh-5.1#
-
# With llvm-path set to /usr/lib
sh-5.1# flutter pub get && dart run ffigen
Running "flutter pub get" in proj...                             2,793ms
Precompiling executable... (2.6s)
Precompiled ffigen:ffigen.
Running in Directory: '/proj'
[WARNING]: Prefer adding Key '[name]' to your config.
[WARNING]: Prefer adding Key '[description]' to your config.
[SEVERE] : Couldn't find dynamic library in default locations.
[SEVERE] : Please supply one or more path/to/llvm in ffigen's config under the key 'llvm-path'.
[SEVERE] : Couldn't find libclang dynamic library in specified locations.
```

Here is my pubspec.yaml:
```yaml
name: greeter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ffi: ^1.0.0
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  ffigen: ^2.4.0

flutter:
  uses-material-design: true

ffigen:
  output: 'lib/generated_bindings.dart'
  llvm-path:
    - '/usr/lib/'
  headers:
    entry-points:
      - 'rust/target/greeter.h'
```
