### ISSUE TITLE
[Question] Not worked on windows.

### ISSUE THREAD

**Issue by TENX-S** [dart-lang/ffigen#210]
Hi, I went into trouble when dealing these things on Windows 10.
When I run `dart run ffigen`, it reports an error:
```powershell
❯ dart run ffigen
Could not find a file named "pubspec.yaml" in "C:\Users\Ares\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\boolean_selector-2.1.0".
```

The `pubspec.yaml` of my project:
```yaml
name: greeter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^2.4.2

flutter:

  uses-material-design: true

ffigen:
  output: lib/bindings.dart
  headers:
    entry-points:
      - rust/target/bindings.h
  name: GreeterBindings
  description: Dart bindings to call rust functions
```

Flutter doctor:
```powershell
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.4)
[✓] Android Studio (version 4.1.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] VS Code, 64-bit edition (version 1.55.2)
[✓] Connected device (3 available)

• No issues found!
```

rust/target/bindings.h:
```c
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

char *rust_greeting(const char *to);

void rust_cstr_free(char *s);
```

Environment:
* Windows 10 20H2
* Visual Studio installed (All components)
* LLVM 11 installed (in the PATH)

My tries:
* `flutter clean`
* `flutter pub cache repair`
* reinstall

But no one is successful. How can I fix it ? Thanks !
