### ISSUE TITLE
Help needed, `libgit2` generate bindings

### ISSUE THREAD

**Issue by nivekithan** [dart-lang/ffigen#213]
Hi, I am trying to create `dart` bindings for [libgit2](https://github.com/libgit2/libgit2) since I could not finding anything similar to this in `pub.dev` . But I got stuck on how to do this, I read the documentation and even looked into examples provided. But still I am not sure how to approach this. 

So please  can anyone explain the process in step by step manner

**Comment by mannprerak2** [comment]
Here's how you can generate the bindings to libgit2 -
1. Get the C source, which should be in [libgit2/include](https://github.com/libgit2/libgit2/tree/main/include)
2. Append this to your `pubspec.yaml` file 
```yaml
ffigen:
  output: 'lib/libgit2_bindings.dart' # This file will be generated.
  headers:
    entry-points:
      - 'libgit2/include/git2.h' # Considering you pasted the source in your project directory.
    include-directives:
      - '**/git2/**.h #  Only the declarations in `git2` folder are generated.
```
3. Run `dart run ffigen` or if this is a flutter project `flutter pub run ffigen`.

I am not sure about the scope of your query, but `package:ffigen` only deals with generating the bindings from C headers, if you have any other queries, consider asking on StackOverflow.
