### ISSUE TITLE
Sharing shared definitions

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffigen#22]
Consider the following scenario:

* header1 - with a struct
* header2 which imports header1 - having that struct in a signature
* header3 which imports header1 - having also that struct in the signature

Now we run the generator on header 2 and 3: they both generate the same struct.
These two structs will be Dart classes with the same name but incompatible.
You can work around that with `Pointer.cast<>()`, but that's not safe.
Also, this increases code size.

It would be better to be able to run the generator on all 3 headers files and let the generated files for header 2 and 3 import the generated file for header 1.

We need to think about a good design for this, especially if headers 2 and 3 are in different dart packages.

(I am not sure how common this scenario is. For example libclang and sqlite3 stand very much on themselves. But I can imagine structs defined in OS APIs fall into this category, so it would be nice to address this.)

**Comment by dcharkes** [comment]
Some high level design questions/remarks.

We have two main use cases:

1. Having reusable library bindings in a separate package (For example standard library bindings.)
2. Having multiple generation steps in a single library. (For example the bindings for a native library and the bindings of some utility C code that the package author likes to keep separate from the native library. For example in [package:webcrypto](https://github.com/google/webcrypto.dart/blob/9a0af9d3596fd50b70087375827c2242d6f96db2/tool/update_bindings.dart)).

These two use cases mean we might both have import urls to _other_ packages as well imports to relative paths.

Then we need to consider the users of reusable libraries, what is the minimal information they need to specify in their `ffigen.yaml`?

1. The absolute minimum is the path to the `symbols.yaml` (possibly in another package).

```yaml
shared-bindings:
  base_h: # we don't actually need this name 
    package: 'foo' # optional, if omitted its a path in the package itself
    path: 'generated/base_symbols.yaml'
```

This means the generated file would need to contain the file paths.

2. We could refer to the `ffigen.yaml` instead, and fish the output path from there. (This would assume the ffigen invocation and the config are always in the same folder.)

**Comment by dcharkes** [comment]
> how are we planning to serve the `symbol.yaml` file to the user? Does pub allow packaging these?

Yes, anything that is not in .gitignore is packaged with a package on pub.

We can find a packageRoot of dependent packages by parsing `.dart_tool/package_config.json` with `package:package_config`, and then find the yaml within the package.

> And perhaps another wild idea could be to use annotations here somehow? Wdyt?

That's a neat idea!

We could generate an annotation with the data in Dart maps/lists/sets/strings instead of putting it in a yaml. We could put it on every individual definition instead of building a map. I don't have so much experience with annotation processing to know how easy it is to find it on all definitions. Alternatively we could put an annotation on the top-class with the full mapping.

One potential downside of annotations is annotation parsing speed vs yaml parsing. We'd need to parse the whole Dart file. I'm not sure if this is a concern, we should check the speed for that.

Another potential downside of annotations is that we can't use a re-export mechanism. For example, I expect to generate bindings in `lib/src/.../*.dart` which should not be imported by other packages. And then re-export those bindings in `lib/<my-package>.dart`.

**Comment by mannprerak2** [comment]
This seems to be a good enough symbol file format to me
```yaml
format_version: 1.0.0
"../generated/base_gen.dart" :
  used_config:
    ffi-native: true # or false
  symbols:
    "c:@E@BaseEnum":
      name: BaseEnum
    "c:@F@base_func1":
      name: base_func1
```
---
>Do we want to version with ffigen or do we want to version the format by itself

How about putting the version of the least supported ffigen version in the generated symbols file? Each ffigen release will have to ensure that if there's a breaking change in symbols file or the generated bindings, we increment the least supported version.

> Do we want to support multi-file: I say yes. Even though right now we don't.

The above symbol file lgtm. We can always increment the format version later if need be.

> For example the @FfiNatives put the symbols in the top level,

How are we planning to use this information?

For libraries with different `ffi-native` flags (`true/false`)
1. Type sharing is only possible for NoLookupBindings so the imports will still work
2. **However** since we are also **not** generating the shared LookupBindings (since they are part of the shared bindings) libraries which have different `ffi-native: ` flag are not compatible. The library author needs to either generate 2 bindings, (for true/false) and 2 symbol files each. Or in case the `ffi-native` flags are incompatible, we generate all the NoLookupBindings instead of excluding them.

**Comment by dcharkes** [comment]
> How about putting the version of the least supported ffigen version in the generated symbols file? Each ffigen release will have to ensure that if there's a breaking change in symbols file or the generated bindings, we increment the least supported version.

We could do that, at the cost of newer versions of ffigen having to be able to keep parsing older format versions. If we need to update that number manually, I think it makes more sense to have a separate version for the format. We could also add a test to ensure we don't forget to bump the number of we break something by:
1. creating a temp folder
2. write a pubspec.yaml with a dev dependency on an older version of ffigen (we pin it in the test)
3. do `dart pub get`
4. write a symbols.yaml and ffigen.yaml
5. do `dart run ffigen`
Then the test should fail if that older ffigen fails to run on the yaml.

> 1. Type sharing is only possible for NoLookupBindings so the imports will still work

Ah, you're correct. We're not actually invoking any of the functions bound to. 🙃 

> 2\. **However** since we are also **not** generating the shared LookupBindings (since they are part of the shared bindings) libraries which have different `ffi-native: ` flag are not compatible.

I think mixing and matching `FfiNative`s with `lookup` is not going to work from a bundling libraries with a Dart of Flutter application point of view. Maybe the `lookup` ones could depend on the `FfiNative` ones, e.g. the bundling question should be solved by the Dart infrastructure later for `FfiNative`s, so layering `lookup` with which bundling/finding the dynamic library is manual could work.

How are they not compatible in the generated code? Can you paste a snippet with an example?

**Comment by dcharkes** [comment]
Maybe it would be slightly cleaner to put the map with files under its own key.

```yaml
format_version: 1.0.0
files:
  "../generated/base_gen.dart" :
    used_config:
      ffi-native: true # or false
    symbols:
      "c:@E@BaseEnum":
        name: BaseEnum
      "c:@F@base_func1":
        name: base_func1
```

Then we don't have to disambiguate `format_version` and any other top level keys we add from file paths.

**Comment by mannprerak2** [comment]
> How are they not compatible in the generated code? Can you paste a snippet with an example?

But say there's a Base library that is exported by some other library with `ffi-native: true`. Someone now wants to share the base library bindings but want to use dynamic linking. If they use the shared symbol file, we'll end up not generating the functions in base library. So the user is forced to just generate the bindings by themselves now.

**Comment by mannprerak2** [comment]
```yaml
library-imports:
  old_format: 'old/format/still/works.dart'
  base_h:
    symbol-file: '../generated/base_symbols.yaml'
    import-path: '../generated/base_gen.dart' # Optional, can be used to override the value in symbol-file.
```

If a symbol-file has multiple paths, how do we update this config? since a library import is mapped to a single import statement (`import something.dart as lib_name`)?

I can't really see any drawbacks of symbol file with only 1 import. The shared library can always have/generate multiple symbol files, otherwise a single file `exporting` multiple files is also an option.

**Comment by dcharkes** [comment]
> I can't really see any drawbacks of symbol file with only 1 import. The shared library can always have/generate multiple symbol files, otherwise a single file `exporting` multiple files is also an option.

It would be rather inconvenient if we would  generate mappings into multiple files in the future. For example if we a huge C lib with multiple header files and we'd like the Dart bindings to be split among different files the same way. Now, if some other ffigen invocation wants to use all those generated bindings, but we generate a single symbol file per generated Dart bindings file, the other library has to list N symbol files to import. I'd much prefer the other library only listing 1 file to import. Or did you mean to ask something else?

> If a symbol-file has multiple paths, how do we update this config? since a library import is mapped to a single import statement (`import something.dart as lib_name`)?

Why do we need a `lib_name`? Can we invent one? The import name used is just something internal to the generated file, correct?

**Comment by mannprerak2** [comment]
>Why do we need a lib_name? Can we invent one? The import name used is just something internal to the generated file, correct?

Yeah, this is used as the import name.

I guess we can use this as the import prefix when there are multiple files involved.

**Comment by dcharkes** [comment]
> ```yaml
> library-imports:
>   old_format: 'old/format/still/works.dart'
>   base_h:
>     symbol-file: '../generated/base_symbols.yaml'
>     import-path: '../generated/base_gen.dart' # Optional, can be used to override the value in symbol-file.
> ```

If the default new use case is not not overwriting the `import-path`, and if the `lib_name` can be invented, writing it out as 

```yaml
library-imports:
  base_h:
    symbol-file: '../generated/base_symbols.yaml'
  foo_h:
    symbol-file: '../generated/foo_symbols.yaml'
```

feels verbose.

If we want to remove `lib_name` and invent it. We need to make it a list rather than a map with `lib_name` as the key.
And if it's a list, it needs to be under a key.
And, if we have only the `symbol-file` when not specifying import-path overrides, we could omit the `symbol-file` key.

```yaml
library-imports:
  symbol-files:
    - '../generated/base_symbols.yaml'
    - '../generated/foo_symbols.yaml'
```

And then if you want to overwrite the import-path:

```yaml
library-imports:
  symbol-files:
    - '../generated/base_symbols.yaml'
    -
      symbol-file: '../generated/foo_symbols.yaml'
      import-path: '../generated/foo_gen.dart' 
```

**Comment by dcharkes** [comment]
> One drawback of inventing lib_name is that the user can no longer use a symbol-file import in our type-map configuration manually.

Ah I see, I hadn't realized we also used that identifier in our type-map.

I wonder how common that use case is or not. Do we use the type-map often?

> Or maybe we should keep symbol-file a separate config unrelated to library-imports

That is an option. (That would also not support using it in the `type-map`.)

In some sense the symbol files are like automated library-imports while the library imports and type map are like manual imports. So with that reasoning it does make sense to keep them together, correct?

I would like to understand our current use cases of the `type-map` to understand if we should support it.

The only use case in our whole code base is currently:

```yaml
  # These can be used to map any typedef to a specific native type.
  type-map:
    typedefs:
      'time_t':
        lib: 'ffi'
        c-type: 'Int64'
        dart-type: 'int'
    structs:
      'CXCursorSetImpl':
        lib: 'custom_import'
        c-type: 'CXCursorSetImpl'
        dart-type: 'CXCursorSetImpl'
```

Which is the example that two type maps. But our actual libclang bindings don't have the type map.

Is the `type-map` a workaround that we used to use because we were not supporting `AbiSpecificInteger`s in the past? But now that we have `AbiSpecificInteger`s, the type-map is a feature that we should deprecate?

**Comment by mannprerak2** [comment]
> I would like to understand our current use cases of the type-map to understand if we should support it.

It's basically manually using types from another library, perhaps one that doesn't have a symbols file in the future. Another use case could be using custom structs that are not yet supported by ffigen but can somehow be written.

I think both features (type-map and symbol-file) can coexist without interfering and there's no overhead of keeping type-map so maybe we should defer deprecating it later (if need be).

**Comment by dcharkes** [comment]
> It's basically manually using types from another library, perhaps one that doesn't have a symbols file in the future.

Generating a symbols file should be trivial. So making a PR for such package should be trivial.

> Another use case could be using custom structs that are not yet supported by ffigen but can somehow be written.

Right, but that would then also be solved later.

So I think in some beautiful future, users would only be using symbol files and not writing any library imports or type maps by hand.

I do think it would still make sense to nest it under `library-imports` as:

> ```yaml
> library-imports:
>   symbol-files:
>     - '../generated/base_symbols.yaml'
>     - '../generated/foo_symbols.yaml'
> ```
> 
> ```yaml
> library-imports:
>   symbol-files:
>     - '../generated/base_symbols.yaml'
>     -
>       symbol-file: '../generated/foo_symbols.yaml'
>       import-path: '../generated/foo_gen.dart' 
> ```

We'd also need to specify `symbol-file` as output.

In JNIgen I proposed the following output structure: https://github.com/dart-lang/jnigen/issues/88

Should we also have an output structure in the yaml for FFIgen?

**Comment by mannprerak2** [comment]
> I do think it would still make sense to nest it under library-imports

`library-imports` currently expects arbitrary key-value pairs, key: library name, value: path 
Nesting it under is doable but not very clean (both implementation and documentation wise)

And since type-map can no longer use a symbol-file import, I'd still prefer an independent config like
```yaml
symbol-file-import:
    - '../generated/base_symbols.yaml'
    -
      symbol-file: '../generated/foo_symbols.yaml'
      import-path: '../generated/foo_gen.dart' 
    
```
 
> We'd also need to specify symbol-file as output.

We can follow suit to the your proposed structure and unify it with the output config while keeping it backwards compatible 

```yaml
output:
    bindings: path/to/bindings
    symbol-file: path/to/symbol/file
```

Now the question of how import-path and bindings out will change for multiple import paths in the symbol-file still remains?
Since in the future we may want to add support for multiple files being listed in the symbol file

**Comment by dcharkes** [comment]
> And since type-map can no longer use a symbol-file import, I'd still prefer an independent config like
> 
> ```yaml
> symbol-file-import:
>     - '../generated/base_symbols.yaml'
>     -
>       symbol-file: '../generated/foo_symbols.yaml'
>       import-path: '../generated/foo_gen.dart' 
>     
> ```

Can we call it `import`? (Is there anything else we would ever like to import?)

Or

```yaml
import:
  symbol-files:
    - '../generated/base_symbols.yaml'
    -
      symbol-file: '../generated/foo_symbols.yaml'
      import-path: '../generated/foo_gen.dart' 
```

I'm just kind of brainstorming here. This would make `import`->`symbol-files` and `output`->`symbol-file` each others' dual.

> ```yaml
> output:
>   bindings: path/to/bindings
>   symbol-file: path/to/symbol/file
> ```

sgtm

> Now the question of how import-path and bindings out will change for multiple import paths in the symbol-file still remains?
> Since in the future we may want to add support for multiple files being listed in the symbol file

Maybe we leave that for when we get to it then. Or do you have any suggestions.

**Comment by mannprerak2** [comment]
> Can we call it import?
sgtm

> Maybe we leave that for when we get to it then. 

Cool

**Comment by mannprerak2** [comment]
@dcharkes I've pushed changes according to above discussion (#468).
Some more discussion points -
```yaml
import:
  symbol-files:
    -
      symbol-file: '../generated/foo_symbols.yaml'
      import-path: '../generated/foo_gen.dart' 

output:
  bindings: path/to/bindings
  symbol-file: path/to/symbol/file
```

1. The `import-path` is not really making sense here, since the symbol file is designed to be able to declare more than a single file. Maybe we remove it? And we only allow package Uris in generated symbol file yaml?
2. `output->symbol-file` here cannot just be a string, since the import path (ideally a package import) is also needed for the symbol file. 
We can let it be a string, and use `output->bindings` as the import path. We can also mandate `output->bindings` to be a package uri.
