### ISSUE TITLE
Use comments from .c files when generating from .h headers

### ISSUE THREAD

**Issue by hacker1024** [dart-lang/ffigen#228]
I need to generate Dart code from several C header (`.h`) files, with documentation in the C (`.c`) implementation files.

As far as I'm aware, there's no way to do this.

**Comment by mannprerak2** [comment]
You can simply specify the `.c` files instead of the `.h` file. 

Just make sure to specify them in the correct order, so that any C file corresponding to its header, which is included in your source file is parsed first. Otherwise, ffigen will parse the `.h` file first and use the comments from those.

**Comment by hacker1024** [comment]
The header files define the library's public API. If I use the `.c` files, code may be generated to call functions internal to the library, which isn't ideal.

**Comment by mannprerak2** [comment]
In that case you will need to specify which functions to generate. If there is a fixed prefix for the public api functions you are in luck otherwise you will need to manually specify each of them.

```yaml
headers:
  entry-points:
     - your_file_1.c
   include-directives:
     -  **your_file_1.c # This is needed since your implementation file probably imports the header file.
functions:
  include:
    - 'prefix.*' # regexp
```

I can't really think of any other better way to do this.
