### ISSUE TITLE
How to bind many *.h

### ISSUE THREAD

**Issue by fayfive** [dart-lang/ffigen#243]
How to bind so many *.h files? For example, opencv.
And how to write a pubspec.yaml on binding several lib?

**Comment by mannprerak2** [comment]
Hi @fayfive 
You can simply specify the headers using glob syntax

```yaml
ffigen:
  headers:
    entry-points:
      - /path/to/opencv/folder/**.h
    include-directives:
      - '**opencv/**.h'
 ```

For multiple libraries, you can write one `config.yaml` file for each lib, and run `dart run ffigen --config config.yaml` on them.

**Comment by fayfive** [comment]
Thanks!
Is there any samples or article about "config.yaml"？

**Comment by mannprerak2** [comment]
Yeah, it's briefly described in the [config section in readme](https://github.com/dart-lang/ffigen#configurations) 

The only difference is that you pass configurations under the key 'ffigen' in pubspec.yaml and directly when using a separate config.yaml file

**Comment by fayfive** [comment]
@mannprerak2 
I know that. But I want to see the example for multiple lib.
For example, I have two libs. liba libb

ffigen:
  name: liba
  description: Bindings to `liba`.
  output: 'lib/liba.dart'
  headers:
    entry-points:
      - 'liba/include/a.h'

ffigen:
  name: libb
  description: Bindings to `libb`.
  output: 'lib/libb.dart'
  headers:
    entry-points:
      - 'libb/include/b.h'
     
I wrote it in the same yaml. But it does not work.
"Error on line 22, column 1 of pubspec.yaml: Duplicate mapping key."

**Comment by mannprerak2** [comment]
You don't have to add anything to pubspec.yaml, just make 2 files like this -

config1.yaml
```yaml
name: liba
description: bindings to liba
output: 'lib/liba.dart'
...
```

config2.yaml
```yaml
name: libb
description: bindings to libb
output: 'lib/libb.dart'
...
```

Run these commands to generate bindings
`dart run ffigen --config config1.yaml`
`dart run ffigen --config config2.yaml`
