### ISSUE TITLE
Help people generating ignores. Perhaps generate them by default.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/ffigen#270]
See https://github.com/dart-lang/pana/issues/1011

**Comment by jonasfj** [comment]
Specifically, most users of `ffigen` will probably want to inject comments like:
```dart
  // ignore_for_file: camel_case_types, non_constant_identifier_names, unused_element, unused_field
```
In the preamble...

Instead of doing it through the preamble, maybe add an option like `ignore_dart_lints`, example:
```yaml
ffigen:
  output: 'generated_bindings.dart'
  headers:
    entry-points:
      - 'example.h'
  ignore_dart_lints: true # default value being true
```
where `ignore_dart_lints` defaults to `true`, and causes:
```dart
// ignore_for_file: camel_case_types, non_constant_identifier_names, unused_element, unused_field
```
to be inserted after the `preamble`.

That way users of `ffigen` won't have to manually add these `ignore_for_file` stuff in the `preamble`. In practice it's probably rare that users care about the naming convention of generated bindings. Most C libraries won't adhere to our styles anyways.

This is just to make it easier to get the right `ignore_for_file` comments, by doing the right thing by default.
