### ISSUE TITLE
Prefix and replacement for struct/enum members.

### ISSUE THREAD

**Issue by mannprerak2** [dart-lang/ffigen#28]
We currently have no way to add a prefix/replacement name for a struct/enum member.
That means members starting with `_` will be considered private and thus be unusable in our bindings.

**Comment by mannprerak2** [comment]
Possible implementation
```yaml
structs:
  ...
  member-rename:
    for: # to rename members of a particular declaration (exact name must be supplied).
      'CXString':
        '_(.*)': '$1'
    any: # to rename members of any declaration.
      '_(.*)': '$1'
```
First we try to see if `member-rename` -> `for` that particular declaration is provided, apply those.
Otherwise we apply `member-rename` -> `any` is provided.

This is applicable for structs, enums, functions(_parameters names_).

cc @dcharkes
