### ISSUE TITLE
How will YAML change as we add more languages?

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/ffigen#280]
We need to figure out how to adapt the YAML config as we add more languages (eg [ObjC](https://github.com/dart-lang/ffigen/issues/279), Java, Swift, Kotlin).

For the input source files, for Java/Kotlin/Swift we can just look at the file extension, but ObjC also uses .h files. The easiest solution would just be to add an `objc-headers` key, at the same level as `headers`, and I think that would also make sense for the other languages.

The main issue I see is that most of the other top level config keys are either not applicable to some languages (eg `structs`/`typedefs`/`unions`/`macros`), or we'd want them separated by language (eg `functions` might have different naming conventions in different languages, so the regexes would look different).

Should we just add a bunch more top level keys, but with language specific prefixes? Eg `objc-functions`, `java-classes`? Or maybe we should totally restructure the format so that the top level keys so that the language is at the top level:

```
ffigen:
  output:
  c:
    headers:
    functions:
    ...
  objc:
    headers:
    classes:
    ...
```

**Comment by mannprerak2** [comment]
How about adding a top level `lang` key to the config.
```yaml
#  pubspec.yaml
ffigen:
  lang: 'c'
  headers: ...
  functions: ...
```

This still doesn't provide a way to specify multiple configurations in a single file, but that seems rare since bindings would usually be abstracted away as packages. And one can always specify multiple config files in that case. (Each for a different language/binding)

**Comment by liamappelbe** [comment]
@mannprerak2 @dcharkes After Prerak's comment on #313, I think that methods need a different approach. Similar to how member-rename allows renaming a member of a specific struct, I think users are going to want to be able to include/exclude methods of specific interfaces. So having a top level objcMethods config isn't a good idea, as it would apply to all methods in all interfaces. I'm thinking of doing something like this instead:

```yaml
objcInterfaces:
  member-rename:
    'NSString':
      ...
  member-include:
    'NSString':
      - '.*'
  member-exclude:
    'NSString':
      - 'length'
```

So member-rename applies to interface methods the same way it applies to struct members. And member-include/exclude have the same sort of string keys as member-rename, but full include/exclude lists as values.

I might try to land #313 with just the objcInterfaces config key for now, and just remove the objcMethods config, until we figure out the details of how to hand methods.

**Comment by dcharkes** [comment]
That does make a lot of sense indeed. Methods are nested in interfaces/classes in the same way fields are nested in structs.

Given that the member rename for structs is `structs` -> `member-rename` -> [struct match] -> [member match] : [new name], we can follow the same pattern as there as you suggested.

```yaml
structs:
  rename:
    # Removes prefix underscores
    # from all structures.
    '_(.*)': '$1'
  member-rename:
    '.*': # Matches any struct.
      # Removes prefix underscores
      # from members.
      '_(.*)': '$1'
```

I'm wondering if it is worth considering changing up the nesting to: `structs` -> [struct match] -> `member-rename` -> [member match] : [new name]. That would keep all configuration for a single struct, or in this case a single objectiveC interface closer together. cc @mannprerak2, can you remember why we chose the nesting we did for structs? One problem with reversing the order is that `rename` is at the same level as the [struct match].

@liamappelbe wdyt about the nesting order for the config?

**Comment by mannprerak2** [comment]
The nesting order was mostly because we have regexp matching support. So if one wants to do a member rename across all structs, that would be possible (commonly used for removing the prefix underscore)

**Comment by liamappelbe** [comment]
I think nesting rename, include, and exclude under [struct-match] makes logical sense. This would also allow us to unify the `Renamer` and `MemberRenamer`, and reuse the `Includer` rather than building a new `MemberIncluder`.

We'd still be able to do regexp matching on the structs.

**Comment by dcharkes** [comment]
It would be a breaking change for structs API. Though I'm fine with that if we give people a nice migration message on the old syntax.

**Comment by mannprerak2** [comment]
> It is possibly best to do the breaking change for structs first before landing objInterfaces, to keep things consistent.

So are we planning remove the nesting in config then?

**Comment by dcharkes** [comment]
I was thinking something like:

```yaml
structs:
  rename:
    # Removes prefix underscores
    # from all structures.
    '_(.*)': '$1'
  '.*': # Matches any struct.
    member-rename:
      # Removes prefix underscores
      # from members.
      '_(.*)': '$1'
```

Of course, that means we cannot match a struct called `rename` anymore. Or did you have something different in mind @liamappelbe
