### ISSUE TITLE
Question: How to generate bindings for multiple libs, where lib A depends on lib B?

### ISSUE THREAD

**Issue by Jordan-Nelson** [dart-lang/ffigen#285]
Is there a recommended approach for generating bindings for multiple libs, where lib A depends on lib B? The best workaround I have found so far is to generate the bindings for each lib separately, and then write wrapper functions around the generated functions from lib A that use the proper types from lib B.

For example, I am generating bindings for libsecret. libsecret makes use of glib. Below is the definition of one of the core functions from libsecret.

```c
gboolean    secret_password_storev_sync    (const SecretSchema *schema,
  GHashTable *attributes,
  const gchar *collection,
  const gchar *label,
  const gchar *password,
  GCancellable *cancellable,
  GError **error);
```

with a config below

```yaml
output: 'lib/src/generated/libsecret.dart'
name: 'Libsecret'
description: 'Bindings to libsecret'
headers:
  entry-points:
    - '<path_to_libsecret>/libsecret/libsecret/secret.h'
    - '<path_to_libsecret>/libsecret/libsecret/secret-schema.h'
    - '<path_to_libsecret>/libsecret/libsecret/secret-password.h'
```

The following is generated:

```dart
int secret_password_storev_sync(
  ffi.Pointer<SecretSchema> schema,
  ffi.Pointer<ffi.Int32> attributes,
  ffi.Pointer<ffi.Int32> collection,
  ffi.Pointer<ffi.Int32> label,
  ffi.Pointer<ffi.Int32> password,
  ffi.Pointer<ffi.Int32> cancellable,
  ffi.Pointer<ffi.Pointer<ffi.Int32>> error,
) {...}
```

This isn't really what I would hope, since gchar, GHashTable, etc. are all represented as Int32 here.

If I add the following to the config

```yaml
compiler-opts:
- '-I/<path_to_glib>/'
```
I get the following:

```dart
int secret_password_storev_sync(
  ffi.Pointer<SecretSchema> schema,
  ffi.Pointer<GHashTable> attributes,
  ffi.Pointer<gchar> collection,
  ffi.Pointer<gchar> label,
  ffi.Pointer<gchar> password,
  ffi.Pointer<ffi.Int32> cancellable,
  ffi.Pointer<ffi.Pointer<GError>> error,
)
```

This is great, except for one issue. GHashTable, gchar, etc. are part of the generated `Libsecret` lib. This isn't a huge deal for the types, but glib has functions as well, which also get created as part of the generated `Libsecret` lib.

The work around I am using currently is to generate the bindings separately, and then write a wrapper function like so:

```dart
void wrapped_secret_password_storev_sync(
  Pointer<SecretSchema> schema,
  Pointer<GHashTable> attributes,
  Pointer<gchar> collection,
  Pointer<gchar> label,
  Pointer<gchar> password,
  Pointer<Int32> cancellable,
  Pointer<Pointer<GError>> error,
) {
    libsecret.secret_password_storev_sync(
      schema,
      attributes.cast(),
      collection.cast(),
      label.cast(),
      password.cast(),
      cancellable,
      error.cast(),
    );
  }
```

This works, but is sort of tedious. Is there a better approach?

**Comment by liamappelbe** [comment]
Your second approach, where you added `- '-I/<path_to_glib>/'` to the compiler opts, seems reasonable to me. If you don't want the functions from glib, maybe you can try filtering them out using the `functions:` field in the config yaml.

**Comment by Jordan-Nelson** [comment]
I do want some of the functions from lib b actually. I can filter out what I don't want, but then the generated lib is sort of a Frankenstein of two different libs. The functions from lib A and lib B require different dynamic libraries to perform the lookups.

I could create two instances of the generated lib with different dynamic libraries passed in, but then each lib has a bunch of functions that will throw if called.

```dart
final libA = MyGeneratedLib(libADynamicLibrary);
final libB = MyGeneratedLib(libBDynamicLibrary);

// good
libA.func_from_lib_a();
libB.func_from_lib_b();

// this will compile, but throw during the lookup
libA.func_from_lib_b();
```

I could also create classes for `LibA` and `LibB` that have only the appropriate functions, which call through to `MyGeneratedLib`. This is really just a different variation of the original work around (wrapper classes instead of wrapper functions). It might be a little better, but still pretty tedious and error prone.

Is there any way for MyGeneratedLib to accept multiple dynamic libraries? I still don't think that is really the ideal solution I am looking for, but it would be an improvement.

I think ideally I would be able to specify that lib A should import from a certain location for a specific list of types. Basically just a way to tell the generator, "you don't know about this type, but don't worry - here is where you can import it from."

For example, with a config like below, an import for `package:glib/glib.dart` would be added to the generated lib, and `GHashTable` would be used as if it were a type the generator was aware of.

```yaml
output: 'lib/src/generated/libsecret.dart'
name: 'Libsecret'
description: 'Bindings to libsecret'
headers:
  entry-points:
    - '<path_to_libsecret>/libsecret/libsecret/secret.h'
typedefs:
  import-from:
    'GHashTable': 'package:glib/glib.dart'
```

**Comment by liamappelbe** [comment]
There's a bunch of options here:

1. C doesn't really have a concept of libraries at the header level. From the compiler's perspective, it doesn't know that the libB headers are in a different dylib. Everything just gets stuck in the same global namespace. So I don't think it's unreasonable to have everything in one native library, since that's what would happen if you were importing these dylibs into C. You could probably just merge your two dylibs with a clang command, and then load that.
2. Have two separate libraries. LibA has the functions and types from libA, plus the types from dylibB. libB has the functions and types from dylibB. Only catch here is that the dylibB types in the two libraries will be incompatible, but you could write conversion functions. If there's only a few of those types, that would be less work than wrapping all the functions.
3. Like 2, but you use the type-map config field of libA to map all the dylibB types that libA uses to the types from libB. Alternatively you could map them to Dart objects you define yourself.
4. If we can figure out a concrete feature request, we can add explicit handling for this case to ffigen, but I don't see a particularly clean solution. Having a lib that loads multiple dynamic libraries seems really odd to me. But maybe there's a better solution.

**Comment by Jordan-Nelson** [comment]
> Like 2, but you use the type-map config field of libA to map all the dylibB types that libA uses to the types from libB. Alternatively you could map them to Dart objects you define yourself.

Would this use the typedef-map option from the config?

**Comment by liamappelbe** [comment]
`type-map`. Last row in this table: https://github.com/dart-lang/ffigen#configurations

**Comment by Jordan-Nelson** [comment]
Ah, I think that might be exactly what I am looking for. I will try that out and provide and update. Thanks!

**Comment by Jordan-Nelson** [comment]
That is what I was looking for. Thank you!

It looks like the `library-imports` and `type-map` options are only available in the dev release for 5.0.0, which uses the latest dev release of ffi (1.2.0.dev.0). Any idea when there will be stable releases for those two?

Just to summarize for anyone that finds it useful - I am generating the bindings for each lib separately. In the config for Lib A, I am providing the headers for Lib B via `compiler-opts`, adding an import for the generated bindings for Lib B via `library-imports`, and mapping the typedefs from Lib B via `type-map` so that it uses the generated types from Lib B.

Below are simplified versions of my configs:

libsecret (lib A)
```yaml
headers:
  entry-points:
    - '<path_to_libsecret>/libsecret/secret.h'
    - ... other headers
compiler-opts:
- '-I<path_to_glib>/glib/'
library-imports:
  glib: '<path_to_ffigen_output_for_glib>/glib.dart'
type-map:
  'typedefs':
    'GHashTable':
      'lib': 'glib'
      'c-type': 'GHashTable'
      'dart-type': 'GHashTable'
```

glib (lib B)
```yaml
headers:
  entry-points:
    - '<path_to_glib>/glib/ghash.h'
    - ... other headers
```
