### ISSUE TITLE
ObjC: NSData methods are properties are not generated

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/ffigen#345]
When given the header file for NSData, ffigen produces

```
class NSData extends _ObjCWrapper {
  NSData._(ffi.Pointer<ObjCObject> id, NativeLibrary lib) : super._(id, lib);

  static NSData castFrom<T extends _ObjCWrapper>(T other) {
    return NSData._(other._id, other._lib);
  }

  static NSData castFromPointer(
      ffi.Pointer<ObjCObject> other, NativeLibrary lib) {
    return NSData._(other, lib);
  }
}
```

So most interesting methods are missing.

**Comment by liamappelbe** [comment]
Should be. That must be a symptom of the bug.

**Comment by brianquinlan** [comment]
I haven't reduced this, let me know if that would be helpful.

This file:
```yaml
name: ffitest

environment:
  sdk: '>=2.16.0 <3.0.0'

ffigen:
  language: 'objc'
  output: 'nsurlsession_bindings.dart'
  headers:
    entry-points:
      - '/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSURLRequest.h'
      - '/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSURLSession.h'
      - '/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSURL.h'
      - '/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSProgress.h'
      - '/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSURLResponse.h'
      - '/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSHTTPCookieStorage.h'
      - '/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSOperation.h'
      - '/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSError.h'
      - '/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSDictionary.h'
      - '/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSData.h'
      - 'src/urlsessionhelper.h'
  compiler-opts:
    - '-I/Users/bquinlan/dart/flutter/bin/cache/dart-sdk/include/'

dependencies:
  ffi: ^1.1.2
  http: ^0.13.4
  native_library:
    path: ../native_library

dev_dependencies: 
  ffigen:
    path: ../../ffigen
```

Generates this incomplete code:

```dart
class NSData extends _ObjCWrapper {
  NSData._(ffi.Pointer<ObjCObject> id, NativeLibrary lib) : super._(id, lib);

  static NSData castFrom<T extends _ObjCWrapper>(T other) {
    return NSData._(other._id, other._lib);
  }

  static NSData castFromPointer(
      NativeLibrary lib, ffi.Pointer<ObjCObject> other) {
    return NSData._(other, lib);
  }
}
```
