### ISSUE TITLE
Support `@FfiNative`

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffigen#401]
We would like to support generating [`FfiNative` annotations](https://api.dart.dev/stable/2.17.3/dart-ffi/FfiNative-class.html) instead of bindings with based on a `lookup` function.

### Config

The config can be a toplevel switch:

```yaml
ffi-native: true
```

(We could do a filter. But what would be the use case? Conceivably either everything from a header is looked up with the FFI Native Resolver, _or_ with dynamic lookup. Not a mix.)

```yaml
functions:
  ffi-native:
    include:
      # Match function name.
      - 'myFunc'
      # All functions
      - '.*'
    exclude:
      # If you only use exclude, then everything
      # not excluded is `FfiNative`.
      - 'dispose'
```

### Sample output

```c
/** Adds 2 integers. */
int sum(int a, int b);
```

Would generate

```dart
/// Adds 2 integers.
@FfiNative<ffi.Int Function(ffi.Int, ffi.Int>('sum')
external void sum(int a, int b);
```

Note that currently `FfiNative`s are looked up with the lookup function `Dart_SetFfiNativeResolver` in [dart_api.h](https://github.com/dart-lang/sdk/blob/main/runtime/include/dart_api.h). In the future we might want to add support for defining lookups in another way (e.g. `pubspec.yaml`).

This will move `dart:ffi` more in the direction of static binding.

WASM requires static linking, so the [dart2wasm](https://github.com/dart-lang/sdk/tree/main/pkg/dart2wasm) would be using this for FFI to to C files compile to WASM.

#### Top level definitions?

Should the `FfiNative`s be top level or nested inside a class? We do not have a `lookup` function or `DynamicLibrary` to look them up, and the `Dart_SetFfiNativeResolver` can only define a single lookup. So the argument that one could use the bindings for two dynamic librarys / two sets of functions does not apply. So I think it makes sense to have top level definitions.

cc @mannprerak2 Any other design questions that come to mind?

cc @askeksa-google @osa1
