### ISSUE TITLE
[ObjectiveC] Filter interface members

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffigen#419]
ObjectiveC interfaces can be huge.

We should consider supporting filtering interface members.

```yaml
objc-interfaces:
  include:
    - 'AVAudioPlayer'
  member-include:
    -  'AVAudioPlayer'
      -  '.*'
```
