### ISSUE TITLE
LibTorrent bindings

### ISSUE THREAD

**Issue by Davenchy** [dart-lang/ffigen#452]
I am trying to bind libtorrent using ffigen

my `ffigen.yaml`:

```yaml
# Run with `dart run ffigen --config ffigen.yaml`.
name: DartLibTorrentBindings
description: |
  Bindings for `LibTorrent`.

  Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
output: "lib/bindings_generated.dart"
headers:
  entry-points:
    - "src2/include/libtorrent/libtorrent.hpp"
preamble: |
  // ignore_for_file: always_specify_types
  // ignore_for_file: camel_case_types
  // ignore_for_file: non_constant_identifier_names
comments:
  style: any
  length: full
```

the output of `dart run ffigen --config ffigen.yaml` is:

```bash
Input Headers: [src2/include/libtorrent/libtorrent.hpp]
[SEVERE] : Header src2/include/libtorrent/libtorrent.hpp: Total errors/warnings: 1.
[SEVERE] :     src2/include/libtorrent/libtorrent.hpp:4:10: fatal error: 'libtorrent/add_torrent_params.hpp' file not found [Lexical or Preprocessor Issue]
Finished, Bindings generated in /.../flutter/projects/dart_libtorrent/lib/bindings_generated.dart
```

the `libtorrent.hpp` file is something like this

```hpp
// This header is generated by tools/gen_convenience_header.py

#include "libtorrent/add_torrent_params.hpp"
#include "libtorrent/address.hpp"
#include "libtorrent/alert.hpp"
#include "libtorrent/alert_types.hpp"
...
```

I was following this tutorial:

https://blog.logrocket.com/dart-ffi-native-libraries-flutter/

**Comment by liamappelbe** [comment]
clang can't find those headers because it needs an extra include directory. In ffigen.yaml, use the `compiler-opts` option to pass clang a `-I` flag:

```yaml
compiler-opts:
  - '-Isrc2/include/'
```

**Comment by kirill-21** [comment]
> I am trying to bind libtorrent using ffigen
> 
> my `ffigen.yaml`:
> 
> ```yaml
> # Run with `dart run ffigen --config ffigen.yaml`.
> name: DartLibTorrentBindings
> description: |
>   Bindings for `LibTorrent`.
> 
>   Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
> output: "lib/bindings_generated.dart"
> headers:
>   entry-points:
>     - "src2/include/libtorrent/libtorrent.hpp"
> preamble: |
>   // ignore_for_file: always_specify_types
>   // ignore_for_file: camel_case_types
>   // ignore_for_file: non_constant_identifier_names
> comments:
>   style: any
>   length: full
> ```
> 
> the output of `dart run ffigen --config ffigen.yaml` is:
> 
> ```shell
> Input Headers: [src2/include/libtorrent/libtorrent.hpp]
> [SEVERE] : Header src2/include/libtorrent/libtorrent.hpp: Total errors/warnings: 1.
> [SEVERE] :     src2/include/libtorrent/libtorrent.hpp:4:10: fatal error: 'libtorrent/add_torrent_params.hpp' file not found [Lexical or Preprocessor Issue]
> Finished, Bindings generated in /.../flutter/projects/dart_libtorrent/lib/bindings_generated.dart
> ```
> 
> the `libtorrent.hpp` file is something like this
> 
> ```c++
> // This header is generated by tools/gen_convenience_header.py
> 
> #include "libtorrent/add_torrent_params.hpp"
> #include "libtorrent/address.hpp"
> #include "libtorrent/alert.hpp"
> #include "libtorrent/alert_types.hpp"
> ...
> ```
> 
> I was following this tutorial:
> 
> https://blog.logrocket.com/dart-ffi-native-libraries-flutter/

![image](https://user-images.githubusercontent.com/63228361/187964227-f4048acc-5995-405b-8012-b61769cfb007.png)
![image](https://user-images.githubusercontent.com/63228361/187964251-72cdbaf5-1e59-4f83-b8de-437d0e2aa83d.png)
Did you solve this?

**Comment by Davenchy** [comment]
Hey @kirill-21 the answer helped to generate code but I still can't use the generated code because it doesn't contain the actual classes and methods found in libtorrent docs

also the generated code has errors for undeclared types

This is my `ffigen.yaml`:
```yaml
# Run with `dart run ffigen --config ffigen.yaml`.
name: DartLibTorrentBindings
description: |
  Bindings for `LibTorrent`.

  Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
output: "lib/bindings_generated.dart"
headers:
  entry-points:
    - "src2/include/libtorrent/libtorrent.hpp"
compiler-opts:
  - '-Isrc2/include'
preamble: |
  // ignore_for_file: always_specify_types
  // ignore_for_file: camel_case_types
  // ignore_for_file: non_constant_identifier_names
comments:
  style: any
  length: full
```
