### ISSUE TITLE
Some objects are being classified as NSObject 

### ISSUE THREAD

**Issue by leighajarett** [dart-lang/ffigen#486]
I generated bindings for classes in the Apple HealthKit framework, but some of the objects are being classified as NSObject. 

For example:

pubspec.yaml:
```
ffigen:
  name: HealthKit
  description: "Create bindings for the HealthKit APIs"
  language: objc
  output: "lib/healthkit_bindings.dart"
  compiler-opts:
    - '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks'
  exclude-all-by-default: true
  objc-interfaces:
    include:
      - "HKHealthStore"
      - "HKQuery"
  headers:
    entry-points:
      - "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/HealthKit.framework/Headers/HKHealthStore.h"
      - "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/HealthKit.framework/Headers/HKQuery.h"
 ```

```
 var healthStore = hk.HKHealthStore.alloc(lib).init();
```

`healthStore` is an `NSObject` as opposed to a `HKHealthStore`. 

This can be fixed with:

```
var healthStore = hk.HKHealthStore.castFrom(hk.HKHealthStore.alloc(lib).init());
```

This is for a tutorial for Apple developers, so should the general guidance be that `.castFrom()` is used in places where dart is recognizing the object as `NSObject`? Is it considered a bug or expected behavior?
