### ISSUE TITLE
Pointer<Utf8> filter

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ffigen#488]
If we have a header file for which we know all the `char*` are UTF-8 null-terminated strings, we can do the following:

```c
int my_strlen(char *a);

char *my_substr(char *a, int start, int end);
```

```yaml
  type-map:
    native-types:
      'char':
        'lib': 'pkg_ffi'
        'c-type': 'Utf8'
        'dart-type': 'Utf8'
```

However, this does not support any `char` (without `*`) in the API.

The following doesn't work:

```yaml
  type-map:
    native-types:
      'char*':
        'lib': 'dart_ffi'
        'c-type': 'Pointer<pkg_ffi.Utf8>'
        'dart-type': 'Pointer<pkg_ffi.Utf8>'
```

Matching on `char*` isn't supported.

Also, there's no way to filter only replacing the type in certain functions but not everywhere.

For libraries that do not have any `char` in their API, and for which all `char*` are consistently `Pointer<Utf8>` this works though.
