### ISSUE TITLE
Missing iOS file when generating bindings for CMPedometer

### ISSUE THREAD

**Issue by leighajarett** [dart-lang/ffigen#493]
Hi! I'm trying to use generate bindings for the CMPedometer class that's part of the CoreMotion framework. But, I am just getting a blank bindings file.

Config:
```
name: PedometerBindings
description: "Bindings for CM pedometer"
language: objc
output: 'lib/pedometer_bindings_generated.dart'
compiler-opts:
  - '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks'
objc-interfaces:
  include:
    - "CMPedometer"
headers:
  entry-points:
    - "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/CoreMotion.framework/Headers/CMPedometer.h"

```

There are a series of Nullability Issue warnings, such as:
```
[SEVERE] :     /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:361:13: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [Nullability Issue]
```

As well as a Lexical or Preprocessor Issue:
```
[SEVERE] :     /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURL.h:10:9: fatal error: 'Foundation/NSURLHandle.h' file not found [Lexical or Preprocessor Issue]
```

Sorry in advance if I am missing something!!

**Comment by liamappelbe** [comment]
The nullability issue is a red herring. The second error is the real problem. One of the headers is trying to include Foundation/NSURLHandle.h and can't find it. This usually means that you're missing an include directory or a framework in your compiler-opts.

**Comment by leighajarett** [comment]
It seems like that file should be in the directory used for compiler-opts?

**Comment by leighajarett** [comment]
Actually I don't see that header file (NSURLHandle.h) in the Foundations framework

**Comment by brianquinlan** [comment]
I think that you just need to add the entry point explicitly. Like:

```
headers:
  entry-points:
    - "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/CoreMotion.framework/Headers/CMPedometer.h"
    - "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSURLHandle.h"
```

Maybe replace your first entry point with the macOS version:
```
headers:
  entry-points:
    - "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreMotion.framework/Headers/CMPedometer.h"
    - "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSURLHandle.h"
```

**Comment by liamappelbe** [comment]
Choosing a different entry point might work as a work-around. But I think the fundamental issue is that you're targeting iOS, but clang thinks you're targeting mac (that's why the `TARGET_OS_OSX || TARGET_OS_MACCATALYST` macro is true). I'll try and find the right compiler flag to get it to target iOS.

**Comment by leighajarett** [comment]
Thanks Brian and Liam. A few follow ups:

Liam that sounds right to me, because I would expect that you use the SDKs for the platform you'll be targeting in your dart code, right? (in this case iOS).

Additionally, I did try using the macOS SDKs, and while I no longer get that error (so long as I list the MacOSX frameworks in the compiler-opts), it still doesn't generate the bindings. I get the same nullability warnings and: 

```
[SEVERE] :     /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreMotion.framework/Headers/CMPedometer.h:189:115: warning: 'visibility' attribute ignored [Semantic Issue]
```

Also, I tried using the exclude for NSURLHandle and that didn't work, is that expected?

**Comment by liamappelbe** [comment]
Found the flag. To target iOS you need to add a minimum iOS version (`mios-version-min`) to your compile opts:

```
  compiler-opts:
    - '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks'
    - '-mios-version-min=13.0'
```

**Comment by liamappelbe** [comment]
> I get the same nullability warnings and:

That warning doesn't look important to me. We should probably add some log spam filters at some point. It's hard to sort through the noise.

> Also, I tried using the exclude for NSURLHandle and that didn't work, is that expected?

Yeah, the exclusions are excluding the class, not the header. Ffigen doesn't even get to the stage where it can start applying those class exclusions, because failing to find the header file is a serious compile error.

**Comment by leighajarett** [comment]
Okay thanks. The error goes away with the minimum ios version flag, but still no bindings are generated. 

```
# Run with `flutter pub run ffigen --config ffigen.yaml`.
name: PedometerBindings
description: "Bindings for CM pedometers"
language: objc
output: "lib/pedometer_bindings_generated.dart"
compiler-opts:
  - '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks'
  - '-mios-version-min=13.0'
objc-interfaces:
  include:
    - "CMPedometer"
headers:
  entry-points:
    - "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/CoreMotion.framework/Headers/CMPedometer.h"
  ```

There is also this warning:

```
[SEVERE] :     warning: using sysroot for 'MacOSX' but targeting 'iPhone'
```
