### ISSUE TITLE
C `size_t` is being mapped to `ffi.Int` instead of `ffi.Size`

### ISSUE THREAD

**Issue by Joao-Peterson** [dart-lang/ffigen#494]
Excuse me but, i'm making a package for a c lib at the moment and i'm getting unaligned struct members because `size_t` is being mapped to `ffi.Int`, and in 64 bits architectures `ffi.Int` is 32 bits, while `ffi.Size` is a 64 bit value.

Struct (generated by ffigen):
```dart
class Matrix extends ffi.Struct {
  /// < matrix columns size
  @ffi.Int()
  external int x;

  /// < matrix rows size
  @ffi.Int()
  external int y;

  /// < pointer to an array of size y that contains pointers to rows of size x
  external ffi.Pointer<ffi.Pointer<ffi.Int>> m;
}
```

Trying to access the `x`, `y` and `m` values gave this:

```dart
final ffi.Pointer<matrix> m;
// ...
// m is initialized with 10 columns and 7 rows 
// ...
final x = matrix.ref.x; // x = 10
final y = matrix.ref.y; // y = 0
final mAddress = matrix.ref.m.address; // m = 7
```

I believe `size_t` should be mapped to `ffi.Size` by default, because it would be correct for 64 bit architectures.

`c_type.dart`
```dart
@Since('2.17')
@AbiSpecificIntegerMapping({
  Abi.androidArm: Uint32(),
  Abi.androidArm64: Uint64(),
  Abi.androidIA32: Uint32(),
  Abi.androidX64: Uint64(),
  Abi.fuchsiaArm64: Uint64(),
  Abi.fuchsiaX64: Uint64(),
  Abi.iosArm: Uint32(),
  Abi.iosArm64: Uint64(),
  Abi.iosX64: Uint64(),
  Abi.linuxArm: Uint32(),
  Abi.linuxArm64: Uint64(),
  Abi.linuxIA32: Uint32(),
  Abi.linuxX64: Uint64(), // <- 
  Abi.linuxRiscv32: Uint32(),
  Abi.linuxRiscv64: Uint64(),
  Abi.macosArm64: Uint64(),
  Abi.macosX64: Uint64(),
  Abi.windowsArm64: Uint64(),
  Abi.windowsIA32: Uint32(),
  Abi.windowsX64: Uint64(),
})
class Size extends AbiSpecificInteger {
  const Size();
}
```

The related issue #272 was 'fixed' by changing it to `ffi.Int`, i'm going crazy?
This is really the intended functionality? 

I tried mapping by hand to circumvent the map for now, but it didn't work :P

`pubspec.yaml`:
```yaml
  type-map:
    typedefs:
      'size_t':
        'lib': 'pkg_ffi'
        'c-type': 'Size'
        'dart-type': 'Size'
```

So i manually altered the generated binding file:
```dart
class Matrix extends ffi.Struct {
  /// < matrix columns size
  @ffi.Size()
  external int x;

  /// < matrix rows size
  @ffi.Size()
  external int y;

  /// < pointer to an array of size y that contains pointers to rows of size x
  external ffi.Pointer<ffi.Pointer<ffi.Int>> m;
}
```

And it worked alright.

**Comment by dcharkes** [comment]
Indeed, `size_t` should be mapped to `Size` in `dart:ffi`.

@Joao-Peterson could you please provide a reproduction?

**Comment by Joao-Peterson** [comment]
@dcharkes sure.

For this given header file:
`matrix.h`:
```c
#ifndef _MATRIX_HEADER_
#define _MATRIX_HEADER_

#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>

typedef struct{
    size_t x;  
    size_t y;  
    int **m;   
}matrix_t;

#endif
```

And this ffigen config:
`pubspec.yaml`:
```yaml
ffigen:
  name: libmatrix
  description: matrix bindings
  output: 'lib/src/bindingsGenerated.dart'
  preamble: |
    // ignore_for_file: type=lint

  headers:
    entry-points:
    - './modules/libmatrix/matrix.h'

  use-supported-typedefs: true

  typedefs:
    exclude:
    - 'size_t'

  type-map:
    'typedefs':
    'size_t':
      'lib': 'pkg_ffi'
      'c-type': 'Size'
      'dart-type': 'Size'
```

The result is:
`bindingsGenerated.dart`:
```dart
...
class matrix_t extends ffi.Struct {
  @ffi.Int()
  external int x;

  @ffi.Int()
  external int y;

  external ffi.Pointer<ffi.Pointer<ffi.Int>> m;
}
...
```

Expected:
`bindingsGenerated.dart`:
```dart
...
class matrix_t extends ffi.Struct {
  @ffi.Size()
  external int x;

  @ffi.Size()
  external int y;

  external ffi.Pointer<ffi.Pointer<ffi.Int>> m;
}
...
```

**Comment by dcharkes** [comment]
I believe you are using an old version of ffigen, this is what I get when I run your reproduction:

```
[SEVERE] : Expected value of key 'type-map -> typedefs' to be of type 'YamlMap'.
[WARNING]: Unknown key - type-map -> size_t.
[SEVERE] : Please fix configuration errors and re-run the tool.`
```

It works for me with the following config:

```yaml
ffigen:
  name: libmatrix
  description: matrix bindings
  output: 'generated_bindings.dart'

  headers:
    entry-points:
    - 'headers/matrix.h'

  # no filters
```

It generates a large file (not filtering anything) which contains:

```dart
class matrix_t extends ffi.Struct {
  @ffi.Size()
  external int x;

  @ffi.Size()
  external int y;

  external ffi.Pointer<ffi.Pointer<ffi.Int>> m;
}
```

FFIgen version 7.2.3.
