### ISSUE TITLE
ffigen does not find shared libraries on nixos system

### ISSUE THREAD

**Issue by your-sudden-death** [dart-lang/ffigen#519]
If GCC libraries are in non-standard paths, ffigen fails to locate them:
Running `flutter pub run ffigen`

with config
```
headers:
  entry-points:
    - '/tmp/nix-shell.Fa8acC/.tmp8JfG6z.h'
  include-directives:
    - '/tmp/nix-shell.Fa8acC/.tmp8JfG6z.h'
comments: false
preamble: |
  // ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

llvm-path:
   - '/nix/store/y79wjra2sis1zya5mm14ify0dvpw8lh7-clang-11.1.0-lib'
   - '/nix/store/k88zxp7cvd5gpharprhg9ah0vhz2asq7-gcc-12.2.0-lib'
```

with `/nix/store/y79wjra2sis1zya5mm14ify0dvpw8lh7-clang-11.1.0-lib/lib` containing:
```
...
│   ├── libclangParse.a
│   ├── libclangQuery.a
│   ├── libclangReorderFields.a
│   ├── libclangRewrite.a
│   ├── libclangRewriteFrontend.a
│   ├── libclangSema.a
│   ├── libclangSerialization.a
│   ├── libclang.so -> libclang.so.11.1
│   ├── libclang.so.11.1
│   ├── libclangStaticAnalyzerCheckers.a
│   ├── libclangStaticAnalyzerCore.a
│   ├── libclangStaticAnalyzerFrontend.a
│   ├── libclangTesting.a
│   ├── libclangTidy.a
│   ├── libclangTidyAbseilModule.a
│   ├── libclangTidyAndroidModule.a
│   ├── libclangTidyBoostModule.a
...
```
and `/nix/store/k88zxp7cvd5gpharprhg9ah0vhz2asq7-gcc-12.2.0-lib/lib` containing:
```
│   ├── libssp.so.0 -> libssp.so.0.0.0
│   ├── libssp.so.0.0.0
│   ├── libstdc++fs.la
│   ├── libstdc++.la
│   ├── libstdc++.so -> libstdc++.so.6.0.30
│   ├── libstdc++.so.6 -> libstdc++.so.6.0.30
│   ├── libstdc++.so.6.0.30
│   ├── libstdc++.so.6.0.30-gdb.py
│   ├── libsupc++.la
│   ├── libtsan.la
│   ├── libtsan.so -> libtsan.so.2.0.0
│   ├── libtsan.so.2 -> libtsan.so.2.0.0
```

yields:
```
Unhandled exception:
Invalid argument(s): Failed to load dynamic library '/nix/store/y79wjra2sis1zya5mm14ify0dvpw8lh7-clang-11.1.0-lib/lib/libclang.so': /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by //nix/store/wf5c2c7fb2xdf7b8p48vrfkvik249pm6-llvm-11.1.0-lib/lib/libLLVM-11.so)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      initializeGlobals (package:ffigen/src/header_parser/data.dart:50:33)
#3      initParser (package:ffigen/src/header_parser/parser.dart:49:3)
#4      parse (package:ffigen/src/header_parser/parser.dart:23:3)
#5      main (package:ffigen/src/executables/ffigen.dart:55:19)
<asynchronous suspension>
pub finished with exit code 255
```
any ideas? ldd for `/nix/store/wf5c2c7fb2xdf7b8p48vrfkvik249pm6-llvm-11.1.0-lib/lib/libLLVM-11.so` is showing:

```
...
	libxml2.so.2 => /nix/store/yz7qfy85damywy6397vp7nqly0y4qm2r-libxml2-2.10.3/lib/libxml2.so.2 (0x00007f921a29a000)
	libstdc++.so.6 => /nix/store/k88zxp7cvd5gpharprhg9ah0vhz2asq7-gcc-12.2.0-lib/lib/libstdc++.so.6 (0x00007f921a000000)
	libm.so.6 => /nix/store/lqz6hmd86viw83f9qll2ip87jhb7p1ah-glibc-2.35-224/lib/libm.so.6 (0x00007f9219f20000)
...
```
thanks in advance
