### ISSUE TITLE
More fine-grained control on which structs to generate as opaque.

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/ffigen#555]
`dependency-only: opaque` is useful.

But I have some edge cases where I actually want some structs which are only exposed as pointers, but not others. I am just generating all of them now.

This is not a big problem tbh. But from code size perspective, would be nice to mark a struct manually as opaque.

I don't know if this a common problem or unique to my use case.

**Comment by mahesh-hegde** [comment]
>   dependency-only:
>    opaque:
>      '.*': # Matches any struct.

SGTM.

It's to shrink a 3500-line generated file in JNI support library. Currently I am putting it to medium priority. Will take a look at coming weekends.

**Comment by mannprerak2** [comment]
Sounds useful atleast for the code size perspective in the repository.

> But from code size perspective, would be nice to mark a struct manually as opaque.

Would it really matter though for the final build? I mean wouldn't tree shaking eliminate all unused code? @dcharkes

**Comment by mahesh-hegde** [comment]
The former interpretation - for repository and the analysis tools such as IDE.

**Comment by dcharkes** [comment]
> Would it really matter though for the final build? I mean wouldn't tree shaking eliminate all unused code? @dcharkes

Final build if it is AOT it should be tree-shaken out.

However, for JIT runtime, and your IDE response for analyzing/formatting/etc. everything is slightly slower. And AOT compilation time is slightly slower.

**Comment by HosseinYousefi** [comment]
> We can change `dependency-only` to take map that from option `opaque` as key to list of value's which are regexes like the `include`.

I think `opaque` alone (without the `dependency-only` would be shorter (actually your comments will remain correct!):

```yaml
structs:
  include:
      - 'CX.*'
  rename:
    '_(.*)': '$1' # Removes prefix underscores from all structures.
  member-rename:
    '.*': # Matches any struct.
      '_(.*)': '$1' # Removes prefix underscores from members.
  # dependency-only: opaque # still valid, maybe give a warning that it could be replaced with `opaque: ['.*']`
  # dependency-only: full   # still valid, maybe give a warning that it could be replaced with `opaque: []`
  opaque:
    '.*': # Matches any struct.
```
