### ISSUE TITLE
Regexp replacement for renaming declarations

### ISSUE THREAD

**Issue by mannprerak2** [dart-lang/ffigen#56]
Currently, we support prefix-replacement for declarations, this should be replaced with something a _bit more powerful_ like a regexp replacement solution.

**Comment by mannprerak2** [comment]
A possible implementation (similar to how vscode search and replace with `$` sign works)

```yaml
functions:
  ...
  rename:
    'clang_(.*)_(.*)': '$1$2'
```
This will rename a function `clang_string_dispose` with `stringdispose`.

Dartpad imp: https://dartpad.dartlang.org/1fea92c700a15c8d28c053f765879757

cc @dcharkes

**Comment by dcharkes** [comment]
Unfortunately, Dart does not have support for `\U` in its regex replace.

```
  final userRegexp = RegExp('clang_(.*)_(.)(.*)', dotAll: true);
  final userReplaceString = r'$1\U$2$3';
```

```
Original String: clang_string_dispose
Renamed to:      string\Udispose
```

Then we could have even made the name proper dartCasing.

**Comment by mannprerak2** [comment]
We will use something like this to point to things/including -
https://gist.github.com/mannprerak2/76c45b13f29408e042e3475d88504fff

Pasting it here for convenience
```yaml
headers:
  entry-points:    
    - path/to/clang-c/index.h  # glob
  include-directives:
    - **clang-c/**             # glob

structs:
  include:
    - CXString
    - CX.*
  exclude:                     # excludes override includes
    - SomeStruct
  rename:
    - CXString: Str            # renamed 'CXString' to 'Str'.
    - _(.*): $1                # removed underscore.

struct-members:
  rename:
    CXString:                  # regex filter to the members of which struct this should apply
        - data: dt             # rename member 'data' of 'CXString' to 'dt'
        - _(.*): $1            # removed underscore from members of 'CXString'
    '.*':
      - data: dt
      - _(.*): '$1'            # removed underscore from members of any struct (which do not match in for)
```

Related issues: #52 #28
