### ISSUE TITLE
Trying to import `NSURLHandle.h` on ios

### ISSUE THREAD

**Issue by cgrand** [dart-lang/ffigen#600]
I get the following error
```
[SEVERE] :     /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURL.h:10:9: fatal error: 'Foundation/NSURLHandle.h' file not found [Lexical or Preprocessor Issue]
```
I tried following #493 which seems similar but this doesn't fix the issue.

`ffigen` section of my `pubspec.yaml`:
```yaml
ffigen:
  name: UIPasteBoard
  description: Bindings for UIPasteBoard.
  language: objc
  output: 'pasteboard_bindings.dart'
  headers:
    entry-points:
      - '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIPasteboard.h'
  compiler-opts:
    - '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks'
    - '-mios-version-min=13.0'
    - '-isysroot'
    - '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk'
  exclude-all-by-default: true
  objc-interfaces:
    include:
      - 'UIPasteboard'
  preamble: |
    // ignore_for_file: camel_case_types, non_constant_identifier_names, unused_element, unused_field, return_of_invalid_type, void_checks, annotate_overrides, no_leading_underscores_for_local_identifiers, library_private_types_in_public_api
```
